openapi: 3.0.2
info:
  title: Custom
  description: used for testing
  version: 1.0.0
servers:
  - url: /api/v3

paths:
  "/additional-properties":
    get:
      operationId: additionalProperties
      responses:
        200:
          description: testing additional properties
          content:
            application/json:
              schema:
                additionalProperties:
                  type: integer
  "/media-example1":
    get:
      operationId: mediaExample1
      responses:
        200:
          description: media example
          content:
            application/json:
              x-mockambo:
                payloadGenerationModes:
                  - mediaExample
              example:
                foo: bar
              schema:
                properties:
                  foo:
                    type: string
  "/media-example2":
    get:
      operationId: mediaExample2
      responses:
        200:
          description: media example
          content:
            application/json:
              x-mockambo:
                payloadGenerationModes:
                  - mediaExample
                mediaExampleSelectorScript: "'default'"
              examples:
                default:
                  value:
                    foo: bar
              schema:
                properties:
                  foo:
                    type: string
  "/all-of":
    get:
      operationId: allOf
      responses:
        200:
          description: allof
          content:
            application/json:
              schema:
                allOf:
                  - required:
                      - foo
                    properties:
                      foo:
                        type: string
                  - required:
                      - bar
                    properties:
                      bar:
                        type: string
  "/loader":
    get:
      operationId: loader
      responses:
        200:
          description: loader
          content:
              application/json:
                schema:
                  $ref: "loader.yaml#/components/schemas/loader"